spring:
  application:
    name: Job_Hub
  datasource:
    url: jdbc:mysql://localhost:3306/job_hub
    username: dai
    password: 123
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signerkey: BHkRPMOnl2ZV6Z0P+H3eHwuq2D1kZioQcox/ujMlfboZNBU/5E/PeJvavUmO2Z1w
  valid-duration: 10  # thoi gian keo dai co hieu luc la 5s
  refreshable-duration: 120 # thời gian có thể làm mới 120s
