spring:
  application:
    name: Job_Hub
  datasource:
    url: jdbc:mysql://localhost:3307/job_hub
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signerkey: BHkRPMOnl2ZV6Z0P+H3eHwuq2D1kZioQcox/ujMlfboZNBU/5E/PeJvavUmO2Z1w
  valid-duration: 3600  # thời gian kéo dài có hiệu lực là 3600s
  refreshable-duration: 36000  # thời gian có thể làm mới 36000s
